CREATE VIEW VISTA_SIN_CLIENTE AS
SELECT CLIENTES.COD_CLIE AS CODIGO_CLI, 
    PEDIDOS.COD_CLIE AS CODIGO_PED, 
    PEDIDOS.VAL_ESTA_PEDI AS ESTADO_PED
FROM CLIENTES
FULL OUTER JOIN PEDIDOS
ON (CLIENTES.COD_CLIE = PEDIDOS.COD_CLIE)
WHERE PEDIDOS.COD_CLIE IS NOT NULL
AND PEDIDOS.VAL_ESTA_PEDI <> 'RECHAZADO';