CREATE VIEW VISTA_SIN_PEDIDO AS
SELECT CLIENTES.COD_CLIE AS CODIGO_CLI, 
       PEDIDOS.COD_CLIE AS CODIGO_PED, 
       CLIENTES.VAL_NOM1 AS NOMBRE_CLI,
       CLIENTES.VAL_APE1 AS APELLIDO_CLI,
       PEDIDOS.VAL_ESTA_PEDI AS ESTADO_PED
FROM PEDIDOS
INNER JOIN CLIENTES ON PEDIDOS.COD_CLIE = CLIENTES.COD_CLIE
WHERE PEDIDOS.VAL_ESTA_PEDI <> 'FACTURADO';